# This is a basic workflow to help you get started with Actions

name: Deploy to GitHub Pages

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-to-github-pages:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
    # uses GitHub's checkout action to checkout code form the master branch
    - uses: actions/checkout@v2
    # sets up .NET Core SDK 3.1
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1
    # publishes Blazor project to the release-folder
    - name: Publish .NET Core Project
      run: dotnet publish XmasEveCounter.csproj -c Release -o release --nologo
      # changes the base-tag in index.html from '/' to 'XmasEveCounter' to match GitHub Pages repository subdirectory
    - name: Change base-tag in index.html from / to XmasEveCounter
      run: sed -i 's/<base href="\/" \/>/<base href="\/XmasEveCounter\/" \/>/g' release/wwwroot/index.html
    # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll
    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: release/wwwroot

